# Basic site config
title: "IrisOLED"
description: "Arduino library for expressive robotic OLED eyes (SSD1306 / SH1106)."
baseurl: "/Irisoled"        
url: "https://orji123.github.io"  

# Theme
theme: jekyll-theme-minimal

# Markdown processor
markdown: kramdown
author: "Chijindu-Orji Iseh-Ntah"
email: "chijipeters2@gmail.com"   
logo: "/assets/logo.png"        

# Permalinks and build
permalink: /:path/
exclude:
  - README.md
  - LICENSE
